### ISSUE TITLE
BUG: test for admin fails

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/django-dynamic-theme#50]
ERROR: test_theme_file_defined_by_admin (tests.test_context_processor.ThemeTest.test_theme_file_defined_by_admin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/django-dynamic-theme/django-dynamic-theme/tests/test_context_processor.py", line 17, in test_theme_file_defined_by_admin
    admin_theme = Theme.objects.create(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/django-dynamic-theme/django-dynamic-theme/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/django-dynamic-theme/django-dynamic-theme/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/runner/work/django-dynamic-theme/django-dynamic-theme/django_dynamic_theme/models.py", line 113, in save
    self.write_export()
  File "/home/runner/work/django-dynamic-theme/django-dynamic-theme/django_dynamic_theme/models.py", line 106, in write_export
    scss_editor.write(self.export())
  File "/home/runner/work/django-dynamic-theme/django-dynamic-theme/django_dynamic_theme/utill/scss_editor.py", line [24](https://github.com/Segelzwerg/django-dynamic-theme/actions/runs/8580933102/job/23517489812?pr=14#step:8:25), in write
    with open(self._file, mode="w", encoding="UTF-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/Admin.scss'

**Comment by Segelzwerg** [comment]
Actually not fixed
